# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.3

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - docker-php-ext-install pdo_mysql
          - /usr/bin/mysqld_safe &
          - sleep 5
          - cd slim
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - php /usr/local/bin/composer install
          - mkdir cache
          - echo '<?php const DB_HOST = "localhost";
            const DB_USER = "my_app";
            const DB_PASS = "secret";
            const DB_DBNAME = "spil";

            const ACCESS_TOKEN = "1111";
            const PUSH_URL = "https://api.line.me/v2/bot/message/push";
            const PROFILE_URL = "https://api.line.me/v2/profile";
            const GROUP_URL = "https://api.line.me/v2/bot/group/";
            const GROUP_ID = "2222";
            const PUSH_KEY = "spil_push";

            const ROOT_URL = "https://www.spildev.hetabun.com/"; ' > src/settings_param.php
          - vendor/bin/phpunit
        services:
          - mysql

definitions:
  services:
    mysql:
      image: mysql
      environment:
        MYSQL_DATABASE: spil
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USERNAME: my_app
        MYSQL_PASSWORD: secret