<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>スピル管理者メニュー</title>
    <link rel="stylesheet" href="/admin/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/admin/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="/admin/fonts/ionicons.min.css">
    <link rel="stylesheet" href="/admin/css/styles.min.css">
</head>

<body style="background-color:#0099b5;">
    <div class="features-boxed" style="background-color:#0099b5;">
        <div class="container">
            <div class="intro">
                <h2 class="text-center" style="color:rgb(255,255,255);">スピル 管理者ページ</h2>
                <p class="text-center" style="color:#c2c2c2;">管理者専用ページ<br>機能追加依頼はこざさまで</p>
            </div>
            <div class="row justify-content-center features">
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fa fa-calendar-plus-o icon"></i>
                        <h3 class="name">イベント情報追加</h3>
                        <p class="description"></p><a href="../eventpost/" class="learn-more">Select »</a></div>
                </div>
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fa fa-edit icon"></i>
                        <h3 class="name">イベント情報編集</h3>
                        <p class="description"></p><a href="../eventedit/" class="learn-more">Select »</a>
                    </div>
                </div>
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fa fa-user-o icon"></i>
                        <h3 class="name">新規者登録</h3>
                        <p class="description"></p><a href="../newpost/" class="learn-more">Select »</a></div>
                </div>
            </div>
            
            <div class="row justify-content-center features" style="padding-top:0px;">
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box">
                        <h3 class="name">ログアウト</h3><a href="../logout/" class="learn-more">Select »</a></div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="/admin/js/jquery.min.js"></script>
    <script src="/admin/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>