<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>スピル管理者ログインページ</title>
    <link rel="stylesheet" href="/admin/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/admin/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="/admin/fonts/ionicons.min.css">
    <link rel="stylesheet" href="/admin/css/styles.min.css">
</head>

<body>
    <div class="login-dark" style="background-image:url(&quot;/admin/img/IMG_3039.jpg&quot;);margin-top:-150px;">
        <form method="post" style="background-color:#00829b;">
            <h2 class="sr-only">Login Form</h2>
            <div class="illustration"><i class="icon ion-ios-locked-outline" style="color:#ffffff;"></i></div>
            <div><h6 style="color:yellow"><?= htmlspecialchars($error_msg) ?></h5></div>
            <div class="form-group"><input class="form-control" type="user" name="user" placeholder="ID"></div>
            <div class="form-group"><input class="form-control" type="password" name="password" placeholder="Password"></div>
            <div class="form-group"><button class="btn btn-primary btn-block" type="submit" style="background-color:#0f2b5b;">Log In</button></div>
        </form>
    </div>
    <script src="/admin/js/jquery.min.js"></script>
    <script src="/admin/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>