<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>スピル - 名古屋市内のバドミントンサークル</title>
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/css/swiper.min.css">
    <link rel="stylesheet" href="/css/styles.min.css">
    <script>
        window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
    </script>
</head>

<body>
    <div class="jumbotron hero-photography" style="background-image:url(&quot;/img/top.jpg&quot;);margin-bottom:0px;">
        <div class="container" style="width:290px;padding-bottom:3%;padding-top:3%;border:solid 10px;margin-bottom:50px;background-color:rgba(0,0,0,0.63);">
            <h1 class="rubberBand animated hero-title" style="font-size:50px;font-family:Meiryo;font-style:normal;font-weight:bold;margin-top:25px;margin-bottom:10px;">スピル</h1>
            <p class="hero-subtitle" style="font-size:40px;font-family:Meiryo;font-weight:normal;">名古屋市内の<br>バドミントン<br>サークル</p>
        </div>
        <p><a class="btn btn-primary btn-lg hero-button" role="button" href="#learn_more" style="font-family:Meiryo;background-color:#0099b5;">Learn more</a></p>
    </div>
    <div class="highlight-blue" style="background-color:#0099b5;">
        <div class="container">
            <div class="intro">
                <h2 class="text-center" style="font-family:Meiryo;">About</h2>
                <p class="text-center" style="font-family:Meiryo;">名古屋市内の体育館でバドミントンをしましょう！<br>スピルは２０１８年２月から始まった社会人サークルです。<br>人数はまだまだ少ないので、一緒に盛り上げてくれる方を大募集しています！<br><br>活動内容は、部活のような基礎練はあまり行わず、<br>ペアをくじで決めて、簡単な練習とゲームを多めに行います。<br><br>経験者と未経験者の割合は３：７くらいですので、<br>初心者の方も安心してご参加ください！</p>
            </div>
            <div class="buttons"></div>
        </div>
    </div>
    <div class="photo-gallery">
        <h2 class="text-center" style="font-family:Meiryo;font-weight:500;margin-bottom:0;">Gallery</h2>
        <div class="container">
            <div class="row photos" style="padding-top:20px;">
                <div class="col-sm-6 col-md-4 col-lg-3 item"><a href="/img/IMG_3068.jpg" data-lightbox="photos"><img class="img-fluid" src="/img/IMG_3068.jpg"></a></div>
                <div class="col-sm-6 col-md-4 col-lg-3 item"><a href="/img/IMG_3039.jpg" data-lightbox="photos"><img class="img-fluid" src="/img/IMG_3039.jpg"></a></div>
                <div class="col-sm-6 col-md-4 col-lg-3 item"><a href="/img/IMG_3072.jpg" data-lightbox="photos"><img class="img-fluid" src="/img/IMG_3072.jpg"></a></div>
                <div class="col-sm-6 col-md-4 col-lg-3 item"><a href="/img/IMG_3105.jpg" data-lightbox="photos"><img class="img-fluid" src="/img/IMG_3105.jpg"></a></div>
            </div>
        </div>
    </div>
    <div class="simple-slider">
        <div class="swiper-container">
            <div class="swiper-wrapper"></div>
            <div class="swiper-pagination"></div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
        </div>
    </div>
    <div id="learn_more">
        <div class="container">
            <div class="row no-gutters" style="margin-top:50px;margin-bottom:50px;">
                <div class="col-md-6" style="margin-top:10px;margin-bottom:10px;margin-right:0px;">
                    <h2 class="text-center" style="font-family:Meiryo;">Latest schedule</h2>
                    <div class="table-responsive">
                        <table class="table">
                            <tbody>
                                <?php foreach ($latest_info as $info):
                                    $event_date = $info['event_date'].$info['start_time'].' - '.$info['end_time'];
                                    $map_url = 'https://maps.google.co.jp/maps?q='.urlencode($info['place']);
                                ?>
                                <tr>
                                    <td style="font-family:Meiryo;">
                                        <?= htmlspecialchars($event_date); ?> &nbsp;
                                        <a href=<?= htmlspecialchars($map_url);?> target="_blank"style="color:gray;"><?= htmlspecialchars($info['place']); ?></a> 
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-md-6" style="margin-top:10px;margin-bottom:10px;">
                    <h2 class="text-center" style="font-family:Meiryo;">Contact</h2>
                    <center>
                        <img width=50% src="http://qr-official.line.me/L/_9VFfg3tn4.png"><br>
                        <a href="https://line.me/R/ti/p/%40zvl7969n"><img height="36" border="0" alt="友だち追加" src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png"></a>
                    </center>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-basic" style="padding-top:0px;padding-bottom:0px;">
        <footer style="background-color:#0099b5;">
                <div class="social">
                    <iframe src="https://www.facebook.com/plugins/share_button.php?href=https%3A%2F%2Fspil.hetabun.com%2F&layout=button_count&size=small&mobile_iframe=true&appId=218614678873931&width=72&height=20" width="72" height="20" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
                    <a class="twitter-share-button" href="https://twitter.com/share?url=https://spil.hetabun.com/&text=スピル - 名古屋のバドミントンサークル" data-dnt="true">Tweet</a>
                </div>
            <p class="copyright">スピル © 2018</p>
        </footer>
    </div>
    <script src="/js/jquery.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/js/swiper.jquery.min.js"></script>
</body>

</html>