<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-118333967-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-118333967-1');
    </script>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="愛知の名古屋市内で活動するバドミントンサークル
    毎週土日どちらかに３時間程度開催しています！
    サークル目標は「メンバーがアットホームに楽しめる！」です！">
    <meta name="keywords" content="バドミントン,サークル,名古屋,愛知,土日">
    <!--　OG　-->
    <meta property="og:title" content="スピル - 名古屋市内のバドミントンサークル" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="愛知の名古屋市内で活動するバドミントンサークル
    毎週土日どちらかに３時間程度開催しています！
    サークル目標は「メンバーがアットホームに楽しめる！」です！" />
    <meta property="og:url" content="https://spil.hetabun.com/" />
    <meta property="og:image" content="/img/TOP2.jpg" />
    <meta property="og:site_name" content="スピル - 名古屋市内のバドミントンサークル" />
    <title>スピル - 名古屋市内のバドミントンサークル</title>
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/css/swiper.min.css">
    <link rel="stylesheet" href="/css/styles.min.css">
    <script>
        window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
    </script>
</head>

<body>
    <div class="jumbotron hero-photography" style="background-image:url(&quot;/img/top.jpg&quot;);margin-bottom:0px;">
        <div class="container" style="width:290px;padding-bottom:3%;padding-top:3%;border:solid 10px;margin-bottom:50px;background-color:rgba(0,0,0,0.63);">
            <h1 class="rubberBand animated hero-title" style="font-size:50px;font-family:Meiryo;font-style:normal;font-weight:bold;margin-top:25px;margin-bottom:10px;">スピル</h1>
            <p class="hero-subtitle" style="font-size:40px;font-family:Meiryo;font-weight:normal;">名古屋市内の<br>バドミントン<br>サークル</p>
        </div>
        <p><a class="btn btn-primary btn-lg hero-button" role="button" href="#learn_more" style="font-family:Meiryo;background-color:#0099b5;">Learn more</a></p>
    </div>
    <div class="highlight-blue" style="background-color:#0099b5;">
        <div class="container">
            <div class="intro">
                <h2 class="text-center" style="font-family:Meiryo;">About</h2>
                <p class="text-center" style="font-family:Meiryo;">名古屋市内の体育館でバドミントンをしましょう！<br>スピルは２０１８年２月から始まった名古屋で活動する社会人サークルです！<br>人数はまだまだ少ないので、一緒に盛り上げてくれる方を大募集しています！<br><br>活動内容は、部活のような基礎練はあまり行わず、<br>ペアをくじで決めて、簡単な練習とゲームを多めに行います。<br><br>経験者と未経験者の割合は３：７くらいですので、<br>初心者の方も安心してご参加ください！<br><br>メンバー目標は「メンバーがアットホームに楽しめる」です！<br>興味を持たれた方は下のcontactにてご連絡ください！</p>
            </div>
            <div class="buttons"></div>
        </div>
    </div>
    <div class="photo-gallery">
        <h2 class="text-center" style="font-family:Meiryo;font-weight:500;margin-bottom:0;">Gallery</h2>
        <div class="container">
            <div class="row photos" style="padding-top:20px;">
                <div class="col-sm-6 col-md-4 col-lg-3 item"><a href="/img/IMG_3183.jpg" data-lightbox="photos"><img class="img-fluid" src="/img/IMG_3183_s.jpg"></a></div>
                <div class="col-sm-6 col-md-4 col-lg-3 item"><a href="/img/IMG_3039.jpg" data-lightbox="photos"><img class="img-fluid" src="/img/IMG_3039_s.jpg"></a></div>
                <div class="col-sm-6 col-md-4 col-lg-3 item"><a href="/img/IMG_3072.jpg" data-lightbox="photos"><img class="img-fluid" src="/img/IMG_3072_s.jpg"></a></div>
                <div class="col-sm-6 col-md-4 col-lg-3 item"><a href="/img/IMG_3105.jpg" data-lightbox="photos"><img class="img-fluid" src="/img/IMG_3105_s.jpg"></a></div>
            </div>
        </div>
    </div>
    <div class="simple-slider">
        <div class="swiper-container">
            <div class="swiper-wrapper"></div>
            <div class="swiper-pagination"></div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
        </div>
    </div>
    <div id="learn_more">
        <div class="container">
            <div class="row no-gutters" style="margin-top:50px;margin-bottom:50px;">
                <div class="col-md-6" style="margin-top:10px;margin-bottom:10px;margin-right:0px;">
                    <h2 class="text-center" style="font-family:Meiryo;">Latest schedule</h2>
                    <div class="table-responsive">
                        <table class="table">
                            <tbody>
                                <?php foreach ($latest_info as $info):
                                    $event_date = $info['event_date'].$info['start_time'].' - '.$info['end_time'];
                                    $map_url = 'https://maps.google.co.jp/maps?q='.urlencode($info['place']);
                                ?>
                                <tr>
                                    <td style="font-family:Meiryo;">
                                        <?= htmlspecialchars($event_date); ?> &nbsp;
                                        <a href=<?= htmlspecialchars($map_url);?> target="_blank"style="color:gray;"><?= htmlspecialchars($info['place']); ?></a> 
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-md-6" style="margin-top:10px;margin-bottom:10px;">
                    <h2 class="text-center" style="font-family:Meiryo;">Contact</h2>
                    <center>
                        <img src="/img/kozasaprivateQR.jpg" alt="kozaQR" width="200" height="200"><br><br>
                        <a href="http://line.naver.jp/ti/p/lNi_eA4YlY#~"><img height="36" border="0" alt="友だち追加" src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png"></a>
                    </center>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-basic" style="padding-top:0px;padding-bottom:0px;">
        <footer style="background-color:#0099b5;">
                <div class="social">
                <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&autoLogAppEvents=1&version=v2.12&appId=218614678873931';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
                    <!--　LINE -->
                    <div class="line-it-button" style="display: none;" data-type="share-a" data-url="https://spil.hetabun.com/" data-lang="ja"></div>
                    <script src="https://d.line-scdn.net/r/web/social-plugin/js/thirdparty/loader.min.js" async="async" defer="defer"></script>
                    <!--　フェイスブック -->
                    <div class="fb-share-button" data-href="https://spil.hetabun.com/" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fspil.hetabun.com%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">シェア</a></div>
                    <!--　twitter -->
                    <a class="twitter-share-button" href="https://twitter.com/share?url=https://spil.hetabun.com/&text=スピル - 名古屋のバドミントンサークル" data-dnt="true">Tweet</a>
                </div>
            <p class="copyright">スピル - 名古屋市内のバドミントンサークル © 2018</p>
        </footer>
    </div>
    <script src="/js/jquery.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/js/swiper.jquery.min.js"></script>
</body>

</html>